.PHONY:clean all
CC=gcc
CFLAGS=-Wall -g
BIN=01test 02test
all:$(BIN)
.c.o:
#	@echo "run here"
	$(CC) $(CFLAGS) -c $< -o $@
01test:01test.o
	$(CC) $(CFLAGS) $< -o $@
02test:02test.o
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o $(BIN)

